[package]
name = "update_bom"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bom_core = {path = "../bom_core"}
clap = "2.33.3"
